version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./fraud_detection:/app/fraud_detection
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1